import { cn } from '../../lib/cn'

/**
 * The hand-made artwork set (static/images/icons/*.png, generated by
 * scripts/build_icons.py). Lucide covers UI chrome; this is reserved for the
 * places where personality earns its keep - achievements, attributes, badges.
 */
export type ArtworkKey =
  | 'sun'
  | 'coffee'
  | 'workout'
  | 'code'
  | 'chess'
  | 'breakfast'
  | 'lunch'
  | 'water'
  | 'sleep'
  | 'default'
  | 'admin'
  | 'user'

interface ArtworkBadgeProps {
  name: ArtworkKey
  size?: number
  /** Dimmed treatment for locked achievements. */
  locked?: boolean
  className?: string
  alt?: string
}

export function ArtworkBadge({ name, size = 48, locked = false, className, alt = '' }: ArtworkBadgeProps) {
  return (
    <span
      className={cn(
        // Light disc: the artwork is near-black line art, so it would vanish
        // against the dark surfaces it sits on.
        'inline-flex shrink-0 items-center justify-center overflow-hidden rounded-full border border-line bg-artwork-disc',
        locked && 'opacity-35 grayscale',
        className,
      )}
      style={{ width: size, height: size }}
    >
      <img
        src={`/static/images/icons/${name}.png`}
        alt={alt}
        width={size}
        height={size}
        loading="lazy"
        className="size-full object-contain p-[12%]"
      />
    </span>
  )
}
